build:
    dependencies:
        before:
            - cp test/C.txt test/C.php

    environment:
        mysql: 5.7

        override:
            -
                command: './bin/phing unit'
                coverage:
                    file: 'test/coverage.xml'
                    format: 'php-clover'

