build:
    environment:
        mysql: 5.6

    tests:
        before:
            - mysql --version
            - mysql -u root < test/ddl/0100_create_database.sql
            - mysql -u root < test/ddl/0100_create_user.sql
            - mysql -u root test < test/ddl/0100_create_tables.sql
            - mysql -u root test < lib/ddl/0100_create_tables.sql
            - mv test/C.txt test/C.php
            - ./bin/stratum stratum test/etc/stratum.cfg

        after:
            - mv test/C.php test/C.txt

        override:
            -
                command: './bin/phing unit'
                coverage:
                    file: 'test/coverage.xml'
                    format: 'php-clover'

