language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
  
sudo: true

addons:
  mariadb: 5.5

before_install:
  - mysql --version
  - mysql -u root < test/ddl/0100_create_database.sql
  - mysql -u root < test/ddl/0100_create_user.sql
  - mysql -u root test < test/ddl/0100_create_tables.sql
  - mysql -u root test < lib/ddl/0100_create_tables.sql
  - mysql -u root -e "set global binlog_format = 'row';"
  - mysql -u root -e "set global log_bin_trust_function_creators = 1;"
  
install:
  - composer self-update
  - composer update
  - mv test/C.txt test/C.php
  - ./bin/stratum stratum test/etc/stratum.cfg
    
script: 
  - ./bin/phing unit

after_script:
  - mv test/C.php test/C.txt