/**
 * Deletes a BLOB.
 *
 * @param p_cmp_id The ID of the company (safeguard).
 * @param p_blb_id The ID of the BLOB.
 *
 * @type none
 */
create procedure abc_blob_store_blob_del_blob(in p_cmp_id @abc_blob.cmp_id%type@,
                                              in p_blb_id @abc_blob.blb_id%type@)
modifies sql data
begin
  delete from ABC_BLOB
  where cmp_id = p_cmp_id
  and   blb_id = p_blb_id
  ;
end
