/**
 * Deletes a BLOB.
 *
 * @param p_cmp_id The ID of the company (safeguard).
 * @param p_blb_id The ID of the BLOB.
 *
 * @type none
 */
create procedure abc_blob_store_blob_del_blob
(
  in p_cmp_id smallint(5) unsigned, -- type: ABC_BLOB.cmp_id
  in p_blb_id int(10) unsigned --      type: ABC_BLOB.blb_id
)
  modifies sql data
begin
  delete
  from ABC_BLOB
  where cmp_id = p_cmp_id
    and blb_id = p_blb_id;
end
